### ISSUE TITLE
Khó đọc register page ở dark theme

### ISSUE THREAD

**Issue by TamamoNoMae13** [tuananhlai/remind_clone_web_client#13]
![registerD](https://user-images.githubusercontent.com/50830861/99928133-29356000-2d8b-11eb-89d1-5e2cd4aaa43e.png)
Cân nhắc thay bg img vì khi sang dark theme thì chuyển text -> white, mà ảnh lại màu xám.

**Comment by TamamoNoMae13** [comment]
Kèm thêm đổi theme trong app nữa, hiện chỉ có ở ngoài home page/login/register và theme ăn theo vào app luôn.

**Comment by 0x5ea000000** [comment]
không rõ đây là branch nào, branch dev đã có version khác

**Comment by TamamoNoMae13** [comment]
**Branch dev vẫn đang có hiện tượng bị chữ trắng, nền trắng.**
![image](https://user-images.githubusercontent.com/50830861/99948254-88f82f00-2dbc-11eb-89fa-b2cd857eae87.png)
![image](https://user-images.githubusercontent.com/50830861/99948262-8b5a8900-2dbc-11eb-9ba2-11d9b4bb4663.png)
![image](https://user-images.githubusercontent.com/50830861/99948266-8dbce300-2dbc-11eb-8221-cc14ad91381f.png)
**Register cũng tương tự.**
![image](https://user-images.githubusercontent.com/50830861/99948326-a88f5780-2dbc-11eb-8c39-bdd5cf77920a.png)

**Comment by tuananhlai** [comment]
Đã fix.
